### ISSUE TITLE
Feature Request for webpack plugin : new option to disable bundle-stats logger

### ISSUE THREAD

**Issue by jimblue** [relative-ci/bundle-stats#1256]
Hello,
First, thank you for this amazing plugin, I love it!
Actually I only miss an option to toggle your webpack plugin logger.
Users should be able to choose if they want bundle-stats to log info or not.
I can work on a PR if you are interested to add this feature in next release.
Peace

**Comment by vio** [comment]
hi @jimblue, thank you! 🙇 

> Actually I only miss an option to toggle your webpack plugin logger.
I assume you are talking about toggling-off the logs? The plugin is using [`webpack logging API`](https://webpack.js.org/api/logging/) if [available](https://github.com/relative-ci/bundle-stats/blob/master/packages/webpack-plugin/src/webpack-plugin.js#L42-L44) and will fallback to `console` if missing.

PR is welcome ;)

Out of curiosity, do you find the current logs too verbose? If i'm not mistaken, we log only 2-3 lines.

**Comment by jimblue** [comment]
HI @vio, thanks for your lightning fast answer!
Ya, I personally found that the current logs are too verbose for some usage (CI for exemple) and it's always better to let the user choose.
I just made a PR with a new silent option that is false by default, so it will not change anything for current users when upgrading.
Hope you like it and can pop a new release soon 😄 
Peace

**Comment by vio** [comment]
> I just made a PR with a new silent option that is false by default, so it will not change anything for current users when upgrading.

That's perfect, thanks for your contribution @jimblue! 

> Hope you like it and can pop a new release soon

Merged and will be included in the next release - https://github.com/relative-ci/bundle-stats/milestone/5

> Ya, I personally found that the current logs are too verbose for some usage (CI for exemple)

That makes sense ;)

Would love to hear how you use bundle-stats on CI. I am currently working on a service based on bundle-stats that is monitoring the builds and provides GitHub/Slack integrations - https://relative-ci.com
