### ISSUE TITLE
Comparing to previous CI build

### ISSUE THREAD

**Issue by roxeteer** [relative-ci/bundle-stats#1419]
I'm building an application in Jenkins and just introduced `bundle-stats-webpack-plugin` to our webpack config. When I build the app locally, `{ baseline: true }` works nicely for comparing builds, but in our branch-specific Jenkins pipeline I can't rely on npm cache.

Would it be possible to configure input and output paths for `baseline.json` so that we can make our build process read it from the previous build, and store in a known place with every build?

**Comment by vio** [comment]
hi @roxeteer! I think your question is related to https://github.com/relative-ci/bundle-stats/issues/801 

> bundle-stats main usage is for local comparisons, for CI usage i would recommend having a look at http://relative-ci.com (bundle-stats reports with dashboard, github/slack integrations, metrics monitoring).

> If you are still considering doing something custom, i will accept a PR for it, currently this issue is not prioritised. There are couple projects that are relying on a similar flow (eg: [Monitor & Analyze Asset Sizes with Every Build](https://medium.com/naukri-engineering/monitor-analyze-asset-sizes-with-every-build-9c814f6ca8b4))

**Comment by roxeteer** [comment]
Thanks, I'll close this issue as duplicate.
