### ISSUE TITLE
Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by moonrailgun** [relative-ci/bundle-stats#1495]
Hi, I am try to read webpack stats file and throw this error.

Its looks like this stats file is toooo large, and cannot load it in one time.

![image](https://user-images.githubusercontent.com/6964737/120296106-5f373c00-c2fa-11eb-81a6-7cd55e11df93.png)

![image](https://user-images.githubusercontent.com/6964737/120296294-8c83ea00-c2fa-11eb-8466-35383dc8dc30.png)

By the way, the other stats file with `501M` work fine.

**Comment by moonrailgun** [comment]
I am try to read it with stream. but throw error `RangeError: Invalid string length`

After some google, i found this `buffer.constants.MAX_STRING_LENGTH`

In my node version `v14.16.0`, this is `536870888`, and 

```
536870888/1024/1024 = 511.9999771118164
```

so.... is any way to reduce stats.json file size?

**Comment by vio** [comment]
Hi @moonrailgun! The error sounds like a limit on node, I don't think we had cases with files as large as yours.

Depending on the way you output the webpack stats, you can limit the amount of information included by disabling some of the [webpack stats options](https://webpack.js.org/configuration/stats/). You can try first to disable [`sources`](https://webpack.js.org/configuration/stats/#statssource).

Also, you can have a look at [`bundle-stats-webpack-plugin` webpack stats default config](https://github.com/relative-ci/bundle-stats/blob/master/packages/webpack-plugin/src/webpack-plugin.js#L24-L31). The plugin is explicitly setting the required options to avoid processing large amounts of data.

**Comment by moonrailgun** [comment]
Hi, @vio. thanks for your reply.

i just wanna to hear your mind with `sources` because i am not good at webpack. and just generate stats.json file by default config.

I will try to this way later. then i will close this issue by myself.

Thanks again, and if your wanna support large json file, maybe can tries [JSONStream](https://www.npmjs.com/package/JSONStream). its looks can resolve its case

**Comment by vio** [comment]
if you are using the webpack cli to output the stats, add ` stats: { sources: false }` to your `webpack.config.js`.

> Thanks again, and if your wanna support large json file, maybe can tries JSONStream. its looks can resolve its case

Thanks, might be handy, might need to reconsider once we start picking up more data from the webpack stats / sourcemaps

**Comment by moonrailgun** [comment]
set `{ sources: false }` is work, and for my case, the stats.json is reduce to `405M`.

I will be close this issue, and thank for your time

**Comment by njleonzhang** [comment]
@vio  my stats.json is still to big, more than 560M after set srouce to false, can we consider to support large file?

**Comment by moonrailgun** [comment]
> @vio my stats.json is still to big, more than 560M after set srouce to false, can we consider to support large file?

@njleonzhang Hi, for the temporary solution, your can switch to node 12 or below. In those version of `node`, the upstream of v8 set those length is 1g

you can check this value with:
```
buffer.constants.MAX_STRING_LENGTH
```

**Comment by njleonzhang** [comment]
@vio tnx for suggestion, I will try.
> I can not provide my project for reproduction, it's commercial.  :-(
