### ISSUE TITLE
Compressed assets no longer in report

### ISSUE THREAD

**Issue by TREFZ** [relative-ci/bundle-stats#1690]
We use this plugin to compare asset size in a PR against the main branch, which has been great for some time.

Currently we are in the process of upgrading from Webpack 4 to 5 for our application. We use [compression-webpack-plugin](https://www.npmjs.com/package/compression-webpack-plugin) to generate gzip and brotli versions of each asset, and when comparing asset size, we reference the brotli assets as that's what most of our users receive. The issue is that after upgrading Webpack and all relevant packages, we no longer see the compressed assets in the bundle-stats output, only the uncompressed .css and .js versions of the files. However the compressed assets are still being created during Webpack build.

Any idea what may have changed?

This is just a guess, but I noticed this change. Could be related?
https://webpack.js.org/blog/2020-10-10-webpack-5-release/#stats

> Stats differentiate between `files` and `auxiliaryFiles` now.

webpack: 5.48.0
bundle-stats-webpack-plugin: 3.2.0
compression-webpack-plugin: 9.0.0

**Comment by vio** [comment]
Hi @TREFZ, thanks for the info!

I will try the replicate the setup in the following days, let me know if you have one or if you can provide one.

We had similar issues in the past with other plugins not using the [webpack 5 stage property](https://webpack.js.org/api/compilation-hooks/#list-of-asset-processing-stages), but in this case the stage properties are looking ok. The changed assets should be available to bundle-stats-webpack-plugin:
- compression-webpack-plugin: [`PROCESS_ASSETS_STAGE_OPTIMIZE_TRANSFER`](https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/src/index.js#L275)
- bundle-stats-webpack-plugin: [`PROCESS_ASSETS_STAGE_REPORT`](https://github.com/relative-ci/bundle-stats/blob/master/packages/webpack-plugin/src/webpack-plugin.js#L124)

Also, a helpful test will be to output the webpack stats directly from webpack (`webpack --json > webpack-stats.json` - [recommended stats config](https://relative-ci.com/documentation/setup/agent/cli/webpack-cli)) and see if the compressed assets are available on `assets[]`. You can even run bundle-stats cli(`npx bundle-stats webpack-stats.json`) to check if you get the same results as the plugin.

**Comment by TREFZ** [comment]
Thanks @vio 

Good question about the assets json. We actually use a plugin for that, [assets-webpack-plugin](https://www.npmjs.com/package/assets-webpack-plugin) and I can confirm the compressed files aren't in the output, so this likely has nothing to do with bundle-stats. And I didn't realize webpack had its own stats output 🤦  Will try that out!

**Comment by TREFZ** [comment]
Unfortunately it looks like the webpack stats json doesn't include references to the compressed files. I'll keep investigating, and thanks again!

**Comment by vio** [comment]
Thanks for checking @TREFZ! Feel free to reopen if you think there is a way for bundle-stats to include the compressed sizes.
