### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'val')

### ISSUE THREAD

**Issue by daniele-orlando** [relative-ci/bundle-stats#1910]
bundle-stats-webpack-plugin: 3.2.2
@bundle-stats/utils: 3.2.2
convert-units: 3.0.0-beta.3
webpack: 5.65.0

```
TypeError: Cannot read properties of null (reading 'val')
    at formatFileSize (/Users/dan/My/Lab/evilcode/playground-react/node_modules/@eviljs/webpack-config-react/node_modules/@bundle-stats/utils/lib/utils/format.js:34:40)
    at getMetricRunInfo (/Users/dan/My/Lab/evilcode/playground-react/node_modules/@eviljs/webpack-config-react/node_modules/@bundle-stats/utils/lib/utils/metrics.js:39:23)
    at /Users/dan/My/Lab/evilcode/playground-react/node_modules/@eviljs/webpack-config-react/node_modules/@bundle-stats/utils/lib/report/add-row-metric-data.js:18:62
    at Array.map (<anonymous>)
    at /Users/dan/My/Lab/evilcode/playground-react/node_modules/@eviljs/webpack-config-react/node_modules/@bundle-stats/utils/lib/report/add-row-metric-data.js:14:32
    at /Users/dan/My/Lab/evilcode/playground-react/node_modules/@eviljs/webpack-config-react/node_modules/@bundle-stats/utils/lib/report/merge-metrics-by-key.js:21:74
    at Array.reduce (<anonymous>)
    at /Users/dan/My/Lab/evilcode/playground-react/node_modules/@eviljs/webpack-config-react/node_modules/@bundle-stats/utils/lib/report/merge-metrics-by-key.js:21:32
    at Array.map (<anonymous>)
    at mergeMetricsByKey (/Users/dan/My/Lab/evilcode/playground-react/node_modules/@eviljs/webpack-config-react/node_modules/@bundle-stats/utils/lib/report/merge-metrics-by-key.js:16:40)
```

[bundle-stats/packages/utils/src/utils/format.js](https://github.com/relative-ci/bundle-stats/blob/344afc1cdf296792f6deb8bd761beabb42cf75f2/packages/utils/src/utils/format.js#L13)
```js
import configureMeasurements from 'convert-units';

const convert = configureMeasurements({ digital, time });

export const formatDuration = (val) => {
  const res = convert(val).from('ms').toBest();
  // res is null
  return `${round(res.val, 4)}${res.unit}`;
};
```

`configureMeasurements()` from `convert-units` returns **null**.

The regression has been introduced by a recent release of _convert-units_, the `v3.0.0-beta.3` of a few days ago.

https://github.com/convert-units/convert-units/compare/v3.0.0-beta.2...v3.0.0-beta.3

I have opened an issue on _convert-units_ too, to track it.
https://github.com/convert-units/convert-units/issues/229

**Comment by daniele-orlando** [comment]
## Reproduction

1) Download [bundle.zip](https://drive.google.com/file/d/1bJCZbu_tFQlEzzLcILNpjhp_yZOdMjT9/view)
2) `npm run build`
3) Look it failing

**Comment by vio** [comment]
Hi @daniele-orlando, thanks for reporting the issue!

Unfortunately the problem is on bundle-stats side. I was too eager to use `convert-units@3.0.0-beta.2` for tree shaking and the dependency was not pinned causing new installs to get the latest version.

I will have a look at the convert-units changes, but in the meantime I will pin the dependencies and will release a patch version.

**Comment by vio** [comment]
@daniele-orlando please try to install the latest (`3.2.3`). Feel free to reopen if you still have issues ;)

**Comment by daniele-orlando** [comment]
@vio don't mind, I can understand the eagerness of the three shaking. 😁 Thank you very much for the response and the effort!
