### ISSUE TITLE
webpage performance renders it unusable for large bundle

### ISSUE THREAD

**Issue by cdaringe** [relative-ci/bundle-stats#2072]
# Problem

Clicking `assets` tab from `packages` tab locks up window for ~20s

# Research

The flame graph is minimized, so I cannot see exactly what's goin on:

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/1003261/155024006-eadb99db-4b99-4839-b936-4cb734564374.png">

(scroll down 2x the current shown height),

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/1003261/155024071-26ffad4e-1680-4705-8015-fe9a828d927f.png">

and you can see many yellow/orange lines (Minor GCs).

Something is eating up tons of memory, and the relinquishing it.

I have 615 assets.

Trying to see what `initial chunks` are heavy in my `entrypoint`s, ideally with DCE/TreeShaken gzip'd values from modules

**Comment by vio** [comment]
Thanks for creating the issue @cdaringe! From time to time we test agains larger webpack stats and we didn't encounter this issue, but possible to have a regression.

Will try to see if I can replicate, but can you please share what version of bundle-stats are you using? Also, if you can share your webpack stats will be really helpful (you can send it directly to the email available on my profile).

**Comment by cdaringe** [comment]
Hey @vio , thx for the support! I’ll see if I can grab a stat soon!

**Comment by vio** [comment]
@cdaringe [v2.8.9](https://github.com/relative-ci/bundle-stats/releases/tag/v3.2.9) contains some improvements to the assets/packages view (`HoverCard` is setup on asset name mouse over). I tested with some large webpack stats and noticed a 10-20%, thought curious to see how is it working for your case.

Let me know how it goes if you get the chance to try v2.8.9.

**Comment by cdaringe** [comment]
Thx for the notification! I completely forgot to post a stat. I'll try it out and re-open as needed :)
