### ISSUE TITLE
Loosen dependency requirement ranges

### ISSUE THREAD

**Issue by jkillian** [relative-ci/bundle-stats#2157]
Cool project! One thing I happened to notice though was that most of the dependencies of the various `@bundle-stats` packages have hard-coded dependency ranges that only allow one specific version of a dependency. For example:

https://github.com/relative-ci/bundle-stats/blob/b63b25fbbd74cc1ec17153d9d330cd3a6a42c98c/packages/cli/package.json#L48-L54

This generally ends up meaning when people start using your packages, they have to pull in a bunch of duplicate dependencies very similar to ones they may already have installed, which just means more installation time, more space on disk used, and larger `.lock` files that are harder to read and reason about.

Would you consider changing all your dependency requirements to allow patch and minor updates (e.g. `"boxen": "^5.0.0"`)?

**Comment by vio** [comment]
Hi @jkillian, thanks for opening the issue! It is a valid problem, it used to allow minor versions, but changed it due to a problem with the way the internal packages were resolved. Will try to fix it on the next version.

**Comment by vio** [comment]
@jkillian fixed and released as part of  `v3.3.3`, feel free to re-open if you have any issues.

I had a quick look at the overall package footprint, and it looks like there is quite some room for improvement:

![Screenshot 2022-03-26 at 14 00 35](https://user-images.githubusercontent.com/13300/160240584-96a89938-1bed-47fe-91c9-a0effed55fb7.png)


[npm-download-size for bundle-stats@3.3.3](https://arve0.github.io/npm-download-size/#bundle-stats@3.3.3)

Will  try to handle it as part of the work for the next major release: https://github.com/relative-ci/bundle-stats/issues/2168

**Comment by jkillian** [comment]
Wow, very fast fix, thank you! I tried things out in our project and the new ranges and saw lots of improvements (for example, no more duplicate copies of `core-js` or `boxen`) 💯
