### ISSUE TITLE
build is slow when using this webpack plugin

### ISSUE THREAD

**Issue by xdlrt** [relative-ci/bundle-stats#2645]
I wonder how can I find why this plugin makes my project build so slow.

FYI, the project is about 0.6 million lines code.It's definately a huge project.

**Comment by vio** [comment]
hey @xdlrt, thanks for openning an issue!

We do not have other reports about possible perf issues, personally i've been using the cli against some large webpack stats files and the processing and the report generation were under 1s. 

In the case of the webpack plugin, other than processing and generating the report, some time is spent on extratcing the webpack stats. Will be interesting to see the info provided by [speed-measure-webpack-plugin](https://github.com/stephencookdev/speed-measure-webpack-plugin). Also, any extra info that you can provide about your setup (node/webpack/bundle-stats version, size of the webpack stats) will be really helpful

> FYI, the project is about 0.6 million lines code.It's definately a huge project.
How did you measure this?
