### ISSUE TITLE
Bug: "Order by delta" should order by highest absolute delta

### ISSUE THREAD

**Issue by danielbeardsley** [relative-ci/bundle-stats#2980]
Right now, "Order by Delta" orders by the `% Delta` so it's somewhat useless because a new 2KB module can come before a new 100KB module cause they both have a delta of `100%`:

![image](https://user-images.githubusercontent.com/26855/210882312-b3274038-119f-45c4-af34-39f70f4a735f.png)

## Do This
Make `Order By Delta` order by the delta in KB

**Comment by danielbeardsley** [comment]
Looks like this line is the culprit:
https://github.com/relative-ci/bundle-stats/blob/d965a95104d013bbb0f49723d53a68528e92ad73/packages/ui/src/components/bundle-modules/bundle-modules.utils.js#L37-L39

**Comment by vio** [comment]
@danielbeardsley, thanks for creating the issue! 

I agree that sorting after the absolute delta value is more useful. I see you already identified where the sorting is happening, let me know if you are interested in submitting a PR (we will need to apply the change to assets and packages as well)

**Comment by danielbeardsley** [comment]
Pull is open!

**Comment by vio** [comment]
Thank you @danielbeardsley! 🙇  

Merged and released [`v4.1.7`](https://github.com/relative-ci/bundle-stats/releases/tag/v4.1.7)
