### ISSUE TITLE
Big stats file cannot be loaded via fs function

### ISSUE THREAD

**Issue by Yexiaoxing** [relative-ci/bundle-stats#3195]
If any of the generated webpack stats file is bigger than 500M, the built-in fs.readJSON does not work, and throw error:

```
Cannot create a string longer than 0x1fffffe8 characters
```

A possible fix is like https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/423 which uses a chunked method to load the JSON.

Similar issue: https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/492

**Comment by vio** [comment]
@Yexiaoxing, thanks for opening the issue! The error has been shared before, and I plan to add support for large files on the next major version (https://github.com/relative-ci/bundle-stats/issues/2118).

Until then, I recommend optimizing the webpack stats output. You can follow this guide to output only the data required by bundle-stats: https://relative-ci.com/documentation/guides/webpack-stats/webpack-stats-plugin/#optimize-the-webpack-stats-json-file-size
