### ISSUE TITLE
Support baseline.json customization

### ISSUE THREAD

**Issue by sylhero** [relative-ci/bundle-stats#3524]
Hello!
I'm running a mono repo that generates multiple bundles by app name. However, since all apps share the same node_moudles it means we can only have one baseline.json at all times I would like to know if we can specific the location and the name of this baseline.json so that we can write a script to do the comparison with each app's own bundles.

Thanks

**Comment by Ruchika-saini** [comment]
Facing the same issue.
Customized path for baseline.json is needed.

**Comment by vio** [comment]
Thanks for opening the issue @sylhero!

Here is a workaround on how to change the baseline directory if you run the build task(webpack-plugin) or the cli individually: https://github.com/relative-ci/bundle-stats/issues/688#issuecomment-607834798

I will prioritize #801, it is not that easy to setup with a monorepo.

**Comment by vio** [comment]
It can be tested on https://github.com/relative-ci/bundle-stats/issues/801#issuecomment-1670434448

closing in favour of #801
