### ISSUE TITLE
Webpack plugin env var BUNDLE_STATS_BASELINE

### ISSUE THREAD

**Issue by sbai** [relative-ci/bundle-stats#3843]
Hi, I think the way the `BUNDLE_STATS_BASELINE` environment variable is [currently parsed](https://github.com/relative-ci/bundle-stats/blob/master/packages/webpack-plugin/src/webpack-plugin.js#L10) by the webpack plugin might cause some confusion to users of the plugin.

The default value of the option is set using `Boolean(process.env.BUNDLE_STATS_BASELINE)` to parse the string value of the env var. For both the strings `"true"` and `"false"`, this will result in the boolean value `true`, as will any other non-empty string for that matter. So if someone were to do what I just tried to do and set the env var to true or false depending on a condition, it wouldn't work as they expect, and the baseline would still get built.

Leaving the env var unset entirely still works fine to not build a baseline, so that's what I'll do instead, just thought I'd leave a note in case you're amenable to changing the logic to parse `"false"` as boolean `false`, or log a warning. Either one of those would be useful I think.

**Comment by vio** [comment]
Hi @sbai, thanks for opening the issue! I agree the value of the env is misleading, will fix it on the next release.

**Comment by sbai** [comment]
Thank you!
