### ISSUE TITLE
Budgets

### ISSUE THREAD

**Issue by vio** [relative-ci/bundle-stats#385]
- [x] utils: add support for budget insights
- [ ] budget for individual assets (similar to: https://github.com/webpack/webpack/issues/3216)
- [x] ui: Summary - add support for budget info
- [x] ui: BudgetInsights
- [x] ui: Totals - add support for budget insights
- [ ] webpack-plugin: Add support for budget config
- [ ] cli: Add support for budget config

**Comment by rohit-smpx** [comment]
Is this like hard limits for sizes?

**Comment by vio** [comment]
@rohit-smpx The idea is just to highlight assets / metrics that are over a predefined budget, similar with the way [webpack performance](https://github.com/webpack/webpack/issues/3216) is doing it.

I do not have a clear roadmap on how this can be done at the moment, but couple options will be available once [v2](https://github.com/relative-ci/bundle-stats/milestone/3) will be ready.

**Comment by rohit-smpx** [comment]
If custom budgets can be specified then this will be pretty great. And if the warning can be turned into an error on CI environments then that will help catch full module imports.

**Comment by vio** [comment]
>  that will help catch full module imports.

@rohit-smpx Unexpected module/packages imports can be spotted now, but you have to go over the assets changes and decide if the delta is larger than what you will expect. Other steps to check the modules/packages might be necessary. The bigger the project the longer it will take to decide if there is a problem or not.

The budgets will be used just to provide quick feedback if a metric or an asset size is over the budget, but there is no plan to affect the build in any way. The information will be part of the JSON report, so if need it, affecting the build will be a matter of consuming that data and decide what to do with your build based on it.

On [relative-ci.com](https://relative-ci.com) we have more options for quick feedback if a budget is failing:
1. [github check status](https://github.com/relative-ci/bundle-stats/runs/351276019) (currently `neutral` for every job)
2. Slack/Email notification

**Comment by jflayhart** [comment]
@vio could we at least return a `exit 0` or something to tell CI tools that it passed? And then if a budget fails, we send `exit 1`.

**Comment by vio** [comment]
@jflayhart thanks for your feedback, we will probably need to handle this through an optional argument/option for the cli/webpack-plugin
