### ISSUE TITLE
Support base64url hash encoding

### ISSUE THREAD

**Issue by steverep** [relative-ci/bundle-stats#3921]
Currently, the accuracy of cache invalidation stats requires:

1. Hex encoding with length 5-32 characters
2. Prefixed by only either a `-` or `.`

Ref: https://github.com/relative-ci/bundle-stats/blob/b598cdec7ffc13038eaf556161ab92b10535a598/packages/utils/src/webpack/utils.js#L10

Since Webpack can support any encoding available in Node.jS, it would be nice if RelativeCI supported that as well.  In particular, `base64url` encoding is useful to significantly shorten file names without giving up hash bytes.

Unfortunately, simply updating the current regex will not suffice as `base64url` includes `-` (i.e. regex to match would be `[a-zA-Z0-9-_]`).  If `-` is also the prefix and the length is still unknown, it may only match part of the hash.

I guess I'm surprised that this info cannot just be exported with the stats from the bundlers.  Meaning why guess at all what the length and file name patter is?

**Comment by vio** [comment]
@steverep thank you for opening the issue!

> I guess I'm surprised that this info cannot just be exported with the stats from the bundlers. Meaning why guess at all what the length and file name patter is?

Unfortunately, this information is not available in the stats, and all the tools in the space have been relying on the naive approach of stripping the hex hash from the file name.

I am planning to revisit the problem, last time we looked at it was more than 2 years ago to decrease the length of the matched hash to 5  and support preact-cli output: 
- https://github.com/relative-ci/bundle-stats/issues/1543#issuecomment-881658246
- https://github.com/preactjs/preact-cli/issues/1352#issuecomment-665344731

**Comment by steverep** [comment]
> Unfortunately, this information is not available in the stats, and all the tools in the space have been relying on the naive approach of stripping the hex hash from the file name.

Okay, some possible ideas to improve that then:

- The output can include the chunk IDs and names though, correct (e.g. via [`stats.ids` in Webpack](https://webpack.js.org/configuration/stats/#statsids))?  If so, you could just match a patter that expects the hash to follow the name or ID plus any separator, followed by a suffix that begins with a period.  I think that's not perfect though for the improbable case of the hash containing the ID.
- The regex becomes much more tractable if you just know the hash length, so perhaps just make that configurable in the RelativeCI project settings?  Then perhaps it's as simple as allowing the extra characters for the hash.
- Add `~` and `_` to your list of allowed separators as they are both URL safe characters.  Then it would be easy to support `base64url` with the current approach of unknown hash length, with the restriction that only `~` or `.` will work with `base64url`.

**Comment by vio** [comment]
Thanks @steverep! Extending the patterns is the most convenient solution, we do not have to introduce new options or add new steps to the flow, however:

- chunk ids come with their own challanges: different config option and not all the methods are consistent across builds
- there is quite a bit of variation in the asset filename format and hash length, will require a new config

> add ~ and _ to your list of allowed separators as they are both URL safe characters. Then it would be easy to support base64url with the current approach of unknown hash length, with the restriction that only ~ or . will work with base64url.

They are good candidates for the separator.  webpack uses `~` when extracting common chunks, though i can't remember being used as the hash separator. There migth be some corner cases, but def worth trying.

---

BTW, i had a deeper look at the usage of digestHash and the length of hash, will add the info in here for reference

- [webpack configs `483K`](https://github.com/search?q=path%3Awebpack.config&type=code)
- [webpack configs with digestHash `98`]:(https://github.com/search?q=path%3Awebpack.config+hashDigest%3A+&type=code) - some for modules, some with `hex`, a fraction for `base64*`

Also, regarding the hash length, other than the discussion i [linked previously](https://github.com/preactjs/preact-cli/issues/1352#issuecomment-665344731), i found this discussion about git sha: https://stackoverflow.com/a/18134919/5370588

> > Generally, eight to ten characters are more than enough to be unique within a project. One of the largest Git projects, the Linux kernel, is beginning to need 12 characters out of the possible 40 to stay unique.

> 7 digits are the Git default for a short SHA, so that's fine for most projects. The Kernel team has increased theirs several times, as mentioned because they have several hundred thousand commits. So for your ~30k commits, 8 or 10 digits should be perfectly fine.

My conclusion is that when using a hex length of 7 for the asset content hash, there is the same chance of conflict as for the github sha with the condittion:
- the asset is changed on every commit
- the user/cdn cache lives as long as the repo

**Comment by vio** [comment]
@steverep we are open to adding support for base64url encoding via the pattern matching, though it has to be after `~` separator (`.` is already used for cases like `.chunk.js`, `.min.js`).

Is that something that will work for you? Also, have you considered changing the hash encoding to `hex`? Based on the previous notes, a 7-character hex will be as safe as GitHub.

**Comment by steverep** [comment]
My apologies for the delay... 

> @steverep we are open to adding support for base64url encoding via the pattern matching, though it has to be after `~` separator (`.` is already used for cases like `.chunk.js`, `.min.js`).

I don't understand why `.` would have to be eliminated.  It's already used for hex matching.  Looking at your code, it would not be a difficult addition.  You would just have to treat the separator and encoding patterns as one unit.  Am I missing something?

BTW, the regex patterns currently being used are not correct.  They use `|` inside brackets, which will match the `|` character.  A hex match should just be `[a-f0-9]` with no `|`.

> Is that something that will work for you? Also, have you considered changing the hash encoding to `hex`? Based on the previous notes, a 7-character hex will be as safe as GitHub.

Yes, we can consider going back to hex, but probably with 16 characters for a full 64 bit length.  AFAIK, hashing algorithm designs do not take into account dropping bits when looking at avalanche and other properties, so IMHO that risk is not worth the small savings in URL bytes.

**Comment by vio** [comment]
> I don't understand why . would have to be eliminated. It's already used for hex matching. Looking at your code, it would not be a difficult addition. You would just have to treat the separator and encoding patterns as one unit. Am I missing something?

Sorry, I was under the impression it collides with the `HEX.chunk.js` pattern. I tried it, and it passed all the existing tests. 

The changes were published on [`bundle-stats@4.8.0`](https://github.com/relative-ci/bundle-stats/releases/tag/v4.8.0) and are now available on RelativeCI. The following patterns are now supported:

```shell
# hex hash
**/*.HASH.EXT
**/*-HASH.EXT
**/*_HASH.EXT
**/*~HASH.EXT

# base64url hash
**/*.HASH.EXT
**/*~HASH.EXT
```

> BTW, the regex patterns currently being used are not correct. They use | inside brackets, which will match the | character. A hex match should just be [a-f0-9] with no |.

Thanks for reporting it, I fixed it as part of the same release.

---

I am going to close the issue for now, but feel free to reopen if you still have issues after you change the pattern on your side. Thanks again for reporting it!

**Comment by steverep** [comment]
Thanks @vio.  I made the separator change on our end and looks much better now.

**Comment by vio** [comment]
@steverep awesome! https://bit.ly/3ugEU8j looks ok, let me know if you spot any issues ;)
