### ISSUE TITLE
Sort by actual (not absolute) value

### ISSUE THREAD

**Issue by steverep** [relative-ci/bundle-stats#4119]
Table columns use absolute value instead of actual value to sort.  I don't really understand why this is the case as it results in basically an incorrect and non-intuitive sort.  This makes it impossible to separate increases from decreases, which is the point of sorting IMO...

- Sorting ascending, I expect to see the biggest decreases first
- Sorting descending, I expect to see the biggest increases first

Consider a large bundle for example.  Sorting changes ascending is basically useless as the first page of results is nearly always just a bunch of zeros.

**Comment by vio** [comment]
The idea was to show the largest changes first, but i agree that is confusing.  Will fix it on the next release ;)

**Comment by steverep** [comment]
FWIW, I think that's a reasonable default (i.e. absolute value descending), but yeah pressing sort buttons should override that.

**Comment by vio** [comment]
Fix released on [bundle-stats@4.8.4](https://github.com/relative-ci/bundle-stats/releases/tag/v4.8.4) and synchronised to app.relative-ci.com
