### ISSUE TITLE
Clicking duplicate modules/code should show duplicated size

### ISSUE THREAD

**Issue by steverep** [relative-ci/bundle-stats#4296]
Per https://github.com/relative-ci/bundle-stats/issues/3929#issuecomment-1974328104, clicking on the links for a job's duplicated modules or duplicated code should have the duplicated size shown by default in the table.

**Comment by steverep** [comment]
Activity...

**Comment by vio** [comment]
available on [v4.15.0](https://github.com/relative-ci/bundle-stats/releases/tag/v4.15.0) and https://app.relative-ci.com
