### ISSUE TITLE
Module sizes should reflect minification and tree shaking

### ISSUE THREAD

**Issue by steverep** [relative-ci/bundle-stats#4297]
Per comments at https://github.com/relative-ci/bundle-stats/issues/3929#issuecomment-1779932212, ideally the module sizes reported should reflect any tree shaking or minification when inserted in the bundle.  It's certainly not uncommon to use only a few side-effect free methods from a potentially huge package.

I understand that this is an unfortunate limitation of the bundler's statistics output, but it's an issue to track nonetheless.  Some tools such as `webpack-bundle-analyzer` make an attempt to compensate for these effects.

**Comment by vio** [comment]
@steverep This has been mentioned [before](https://github.com/relative-ci/bundle-stats/issues/1598), though for webpack the option has been to accept new sources and merge the data (webpack-bundle-analyzer, sourcemaps). It does not have a high priority, but hopefully, it is something we can start looking into this summer
