### ISSUE TITLE
Module view - compare by module duplicate size

### ISSUE THREAD

**Issue by vio** [relative-ci/bundle-stats#4300]
Introduce a new view that should compare the module duplicate size 

rel: https://github.com/relative-ci/bundle-stats/issues/3929#issuecomment-1974328104

**Comment by vio** [comment]
Available for testing on `bundle-stats@4.14.0-beta.0` and https://app.relative-ci.com:

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/cee6b4f3-2a73-4569-8ecd-9648d41f05ef">

**Comment by steverep** [comment]
Excellent.  Thanks!
