### ISSUE TITLE
Module side panel - show all module information

### ISSUE THREAD

**Issue by vio** [relative-ci/bundle-stats#4301]
Include all module information:

- duplicate size
- total size
- chunk count

rel: https://github.com/relative-ci/bundle-stats/issues/3929#issuecomment-1974328104

**Comment by steverep** [comment]
Activity...

**Comment by vio** [comment]
<img width="1210" alt="image" src="https://github.com/user-attachments/assets/85f3bceb-efb2-4b50-b84a-40ba32bef1c9">

Released on [bundle-stats@v4.14.0](https://github.com/relative-ci/bundle-stats/releases/tag/v4.14.0) and https://app.relative-ci.com

**Comment by steverep** [comment]
@vio I'm getting a chance to play with this now.  The results seem as expected when viewing the table by "size" and then clicking a module.  However, when viewing the table by "duplicate size" or "total size", the results seem to get corrupted and are heavily inflated.

**Comment by vio** [comment]
@steverep thank you for checking! I was able to replicate it, the current metric gets taken into consideration when computing duplicate and total.

**Comment by vio** [comment]
Fix released on [`bundle-stats@v4.14.2`](https://github.com/relative-ci/bundle-stats/releases/tag/v4.14.2) and https://app.relative-ci.com.

**Comment by steverep** [comment]
Awesome.  Thanks!
