### ISSUE TITLE
View chunk modules not working as expected

### ISSUE THREAD

**Issue by steverep** [relative-ci/bundle-stats#4463]
Sometimes when clicking "view chunk modules" from a chunk's detail, I'm taken to a table of modules that is filtered for the chunk I selected but also includes many other chunks.  As an example:

1. Start at https://app.relative-ci.com/projects/ZyS69RCzSjYaQA6vUq06/jobs/3168-HklqBtad39YDBKR9HtX7?dt=table&dtg=
2. Click initial JS
3. Click the "app.js" entry point
4. Click "view chunk modules"

This takes me to a table of modules that is filtered for the app chunk plus 19 other seemingly random chunks:

https://app.relative-ci.com/projects/ZyS69RCzSjYaQA6vUq06/jobs/3168-HklqBtad39YDBKR9HtX7/modules?bm={"filters"%3A"changed-0_c.15-0_c.380-0_c.780-0_c.848-0_c.899-0_c.954-0_c.1076-0_c.1109-0_c.1372-0_c.1398-0_c.1669-0_c.1727-0_c.2198-0_c.2229-0_c.2240-0_c.2444-0_c.2526-0_c.2888-0_c.2948-0_c.2970-0_c.3135-0_c.3410-0_c.3492-0_c.3563-0_c.3605-0_c.3862-0_c.4142-0_c.4414-0_c.4596-0_c.4902-0_c.5068-0_c.5182-0_c.5224-0_c.5296-0_c.5448-0_c.5625-0_c.5857-0_c.6003-0_c.6015-0_c.6188-0_c.6279-0_c.6325-0_c.6384-0_c.6389-0_c.6683-0_c.6688-0_c.6977-0_c.6988-0_c.7029-0_c.7215-0_c.7414-0_c.7589-0_c.7620-0_c.7906-0_c.7968-0_c.7979-0_c.8162-0_c.8380-0_c.8600-0_c.8709-0_c.8807-0_c.9167-0_c.9277-0_c.9417-0_c.9516-0_c.9540-0_c.9671-0_c.9848-0_c.9859-0_c.9884-0_c.9937-0_c.10045-0_c.10350-0_c.10371-0_c.10762-0_c.10835-0_c.10870-0_c.10957-0_c.11014-0_c.11151-0_c.11239-0_c.11298-0_c.11328-0_c.11366-0_c.11573-0_c.11732-0_c.11758-0_c.11961-0_c.12062-0_c.12162-0_c.12177-0_c.12261-0_c.12341-0_c.12606-0_c.12851-0_c.12928-0_c.12940-0_c.13251-0_c.13312-0_c.13386-0_c.13399-0_c.13538-0_c.13879-0_c.13986-0_c.14062-0_c.14095-0_c.14324-0_c.14440-0_c.14659-0_c.14803-0_c.14820-0_c.14827-0_c.14857-0_c.14949-0_c.14984-0_c.15029-0_c.15105-0_c.15268-0_c.15421-0_c.15579-0_c.15708-0_c.16256-0_c.16401-0_c.16658-0_c.16670-0_c.16779-0_c.17014-0_c.17131-0_c.17168-0_c.17344-0_c.17473-0_c.17604-0_c.17935-0_c.18021-0_c.18152-0_c.18265-0_c.18413-0_c.18483-0_c.18657-0_c.18677-0_c.18688-0_c.18921-0_c.18953-0_c.19075-0_c.19110-0_c.19311-0_c.19449-0_c.19814-0_c.19915-0_c.19943-0_c.20042-0_c.20093-0_c.20534-0_c.20593-0_c.20758-0_c.21050-0_c.21254-0_c.21325-0_c.21421-0_c.21464-0_c.21589-0_c.21762-0_c.21973-0_c.22387-0_c.22393-0_c.22513-0_c.22575-0_c.22577-0_c.22609-0_c.22658-0_c.22677-0_c.22984-0_c.23006-0_c.23141-0_c.23372-0_c.23383-0_c.23588-0_c.24058-0_c.24067-0_c.24086-0_c.24108-0_c.24212-0_c.24709-0_c.25067-0_c.25143-0_c.25722-0_c.25724-0_c.25731-0_c.26222-0_c.26240-0_c.26255-0_c.26485-0_c.26564-0_c.26874-0_c.27209-0_c.27248-0_c.27311-0_c.27335-0_c.27350-0_c.27418-0_c.27692-0_c.27840-0_c.27871-0_c.27908-0_c.28011-0_c.28021-0_c.28138-0_c.28225-0_c.28345-0_c.28366-0_c.28464-0_c.28505-0_c.28591-0_c.28681-0_c.29046-0_c.29202-0_c.29293-0_c.29511-0_c.29596-0_c.29600-0_c.29618-0_c.29805-0_c.29853-0_c.29886-0_c.30150-0_c.30277-0_c.30317-0_c.30455-0_c.30673-0_c.30724-0_c.30817-0_c.30858-0_c.30885-0_c.31052-0_c.31065-0_c.31113-0_c.31337-0_c.31352-0_c.31428-0_c.31488-0_c.31699-0_c.32097-0_c.32133-0_c.32318-0_c.32503-0_c.32506-0_c.32513-0_c.32523-0_c.32615-0_c.32640-0_c.32839-0_c.33103-0_c.33135-0_c.33524-1_c.33620-0_c.33643-0_c.34093-0_c.34166-0_c.34222-0_c.34284-0_c.34543-0_c.34667-0_c.34759-0_c.34867-0_c.35130-0_c.35255-0_c.36041-0_c.36112-0_c.36159-0_c.36456-0_c.36527-0_c.36792-0_c.36851-0_c.37023-0_c.37047-0_c.37101-0_c.37135-0_c.37144-0_c.37208-0_c.37341-0_c.37395-0_c.37482-0_c.37543-0_c.37761-0_c.37925-0_c.37954-0_c.37971-0_c.38034-0_c.38559-0_c.38696-0_c.38716-0_c.38815-0_c.39045-0_c.39126-0_c.39163-0_c.39241-0_c.39316-0_c.39412-0_c.39774-0_c.39790-0_c.40097-0_c.40124-0_c.40194-0_c.40220-0_c.40232-0_c.40418-0_c.40625-0_c.40646-0_c.40806-0_c.40840-0_c.41951-0_c.42043-0_c.42056-0_c.42145-0_c.42307-0_c.42311-0_c.42348-0_c.42541-0_c.42642-0_c.42829-0_c.42861-0_c.42988-0_c.42997-0_c.43364-0_c.43579-0_c.43714-0_c.43923-0_c.43964-0_c.43979-0_c.44042-0_c.44110-0_c.44374-0_c.44748-0_c.44774-0_c.44958-0_c.44965-0_c.45278-0_c.45307-0_c.45382-0_c.45441-0_c.45459-0_c.45481-0_c.45494-0_c.45637-0_c.45656-0_c.45805-0_c.45833-0_c.46054-0_c.46123-0_c.46470-0_c.46482-0_c.46599-0_c.46751-0_c.46986-0_c.47214-0_c.47332-0_c.47351-0_c.47420-0_c.47712-0_c.47790-0_c.47916-0_c.47980-0_c.48018-0_c.48156-0_c.48200-0_c.48456-0_c.48498-0_c.48499-0_c.48632-0_c.48649-0_c.48926-0_c.48981-0_c.49137-0_c.49693-0_c.49774-0_c.49789-0_c.49800-0_c.49840-0_c.49974-0_c.50139-0_c.50419-0_c.50461-0_c.50533-0_c.50713-0_c.50988-0_c.51029-0_c.51337-0_c.51419-0_c.51440-0_c.51616-0_c.52321-0_c.52340-0_c.52351-0_c.52505-0_c.52518-0_c.52530-0_c.52571-0_c.52648-0_c.52785-0_c.52796-0_c.52826-0_c.52978-0_c.53506-0_c.53536-0_c.53600-0_c.53856-0_c.53902-0_c.53947-0_c.53990-0_c.54017-0_c.54222-0_c.54347-0_c.54350-0_c.54474-0_c.54478-0_c.54644-0_c.54654-0_c.54834-0_c.54907-0_c.55125-0_c.55228-0_c.55285-0_c.55475-0_c.55540-0_c.55719-0_c.55723-0_c.55834-0_c.56002-0_c.56178-0_c.56675-0_c.56862-0_c.56924-0_c.56992-0_c.57064-0_c.57780-0_c.57802-0_c.57831-0_c.58161-0_c.58284-0_c.58500-0_c.58681-0_c.58876-0_c.59073-0_c.59084-0_c.59122-0_c.59217-0_c.59347-0_c.59617-0_c.59715-0_c.59716-0_c.59792-0_c.59852-0_c.60136-0_c.60306-0_c.60386-0_c.60659-0_c.60819-0_c.61125-0_c.61141-0_c.61165-0_c.61606-0_c.61614-0_c.61622-0_c.62086-0_c.62125-0_c.62223-0_c.62269-0_c.62512-0_c.62632-0_c.62713-0_c.63112-0_c.63223-0_c.63428-0_c.63559-0_c.63608-0_c.63682-0_c.63743-0_c.63789-0_c.63833-0_c.63964-0_c.63989-0_c.64120-0_c.64189-0_c.64351-0_c.64446-0_c.64631-0_c.65044-0_c.65118-0_c.65192-0_c.65211-0_c.65319-0_c.65496-0_c.65800-0_c.65825-0_c.66035-0_c.66175-0_c.66655-0_c.66753-0_c.66802-0_c.66883-0_c.67155-0_c.67302-0_c.67339-0_c.67360-0_c.67422-0_c.67454-0_c.67692-0_c.67703-0_c.67891-0_c.67943-0_c.68639-0_c.68797-0_c.68831-0_c.68943-0_c.69076-0_c.69089-0_c.69204-0_c.69371-0_c.69411-0_c.69448-0_c.69459-0_c.69592-0_c.69701-0_c.69840-0_c.70001-0_c.70056-0_c.70065-0_c.70111-0_c.70120-0_c.70294-0_c.70328-0_c.70358-0_c.70615-0_c.70678-0_c.70873-0_c.71037-0_c.71038-0_c.71460-0_c.71518-0_c.71615-0_c.71932-0_c.71938-0_c.71952-0_c.72211-0_c.72370-0_c.72483-0_c.72492-0_c.72535-0_c.72842-0_c.73040-0_c.73107-0_c.73112-0_c.73130-0_c.73268-0_c.73299-0_c.73666-0_c.73730-0_c.73734-0_c.73925-0_c.73964-0_c.74013-0_c.74159-0_c.74348-0_c.74514-0_c.74515-0_c.74600-0_c.74822-0_c.75027-0_c.75064-0_c.75218-0_c.75444-0_c.75472-0_c.75514-0_c.75600-0_c.75647-0_c.75748-0_c.75817-0_c.75865-0_c.75898-0_c.75928-0_c.76043-0_c.76071-0_c.76078-0_c.76474-0_c.76515-0_c.76584-0_c.76687-0_c.76757-0_c.76904-0_c.77023-0_c.77151-0_c.77560-0_c.77598-0_c.77855-0_c.77875-0_c.77938-0_c.78149-0_c.78272-0_c.78510-0_c.78826-0_c.78828-0_c.78847-0_c.78894-0_c.79069-0_c.79114-0_c.79238-0_c.79433-0_c.79873-0_c.79891-0_c.79943-0_c.80034-0_c.80199-0_c.80505-0_c.80715-0_c.80786-0_c.80907-0_c.80954-0_c.81005-0_c.81042-0_c.81111-0_c.81128-0_c.81292-0_c.81743-0_c.81998-0_c.82045-0_c.82353-0_c.82408-0_c.82491-0_c.82635-0_c.82656-0_c.82687-0_c.82716-0_c.82725-0_c.82807-0_c.82882-0_c.82946-0_c.83107-0_c.83290-0_c.83295-0_c.83331-0_c.83338-0_c.83392-0_c.83587-0_c.84003-0_c.84245-0_c.84297-0_c.84436-0_c.84649-0_c.84659-0_c.84662-0_c.84966-0_c.85097-0_c.85503-0_c.85604-0_c.85685-0_c.85854-0_c.86334-0_c.86476-0_c.86529-0_c.86599-0_c.86796-0_c.86811-0_c.86936-0_c.86964-0_c.87120-0_c.87260-0_c.87374-0_c.87444-0_c.87515-0_c.87785-0_c.87891-0_c.87905-0_c.87907-0_c.87952-0_c.87996-0_c.88064-0_c.88130-0_c.88199-0_c.88201-0_c.88416-0_c.88436-0_c.88556-0_c.88656-0_c.88672-0_c.88943-0_c.89205-0_c.89388-0_c.89525-0_c.89781-0_c.89924-0_c.89936-0_c.89974-0_c.90113-0_c.90129-0_c.90562-0_c.90731-0_c.90769-0_c.91048-0_c.91212-0_c.91381-0_c.91570-0_c.91651-0_c.91926-0_c.92025-0_c.92196-0_c.92415-0_c.92446-0_c.92589-0_c.92717-0_c.92744-0_c.92840-0_c.92997-0_c.93039-0_c.93046-0_c.93092-0_c.93201-0_c.93327-0_c.93482-0_c.93486-0_c.93624-0_c.93910-0_c.93963-0_c.93975-0_c.94074-0_c.94398-0_c.94415-0_c.94555-0_c.94592-0_c.94633-0_c.95047-0_c.95102-0_c.95177-0_c.95223-0_c.95339-0_c.95462-0_c.95605-0_c.95797-0_c.95831-0_c.95873-0_c.95910-0_c.95912-0_c.95913-0_c.95981-0_c.96249-0_c.96391-0_c.96654-0_c.96767-0_c.97641-0_c.97762-0_c.98234-0_c.98359-0_c.98361-0_c.98679-0_c.98776-0_c.98927-0_c.98942-0_c.99038-0_c.99368-0_c.99624-0_c.99629-0_c.99997-0_mft.CSS-0_mft.JS-1_mft.OTHER-0"}&dt=table&dtg=

**Comment by steverep** [comment]
PS - What does work is taking the following steps afterward:

5. Click on a module that's actually in the app chunk
6. Click to view the app chunk modules from that module's details

**Comment by vio** [comment]
@steverep Thanks for the detailed info, I can replicate it as well. Looks like there is a small difference between the filters we are generating when navigating from assets and module chunks.

**Comment by vio** [comment]
Fix released on `bundle-stats@4.13.0-rc.1` and app.relative-ci.com 

Thanks again for reporting the issue @steverep!
