### ISSUE TITLE
[Feature] Configurable baseline directory

### ISSUE THREAD

**Issue by B3zo0** [relative-ci/bundle-stats#558]
I would like to raise a feature request and if you are interested I could help to implement it as well.

I think it would be awesome if the user could pass in an environment variable with a path for the baseline.json file.

My idea is that I commit the baseline.json file to the source control but with the current implementation I can not do that.

**Comment by vio** [comment]
@B3zo0 the use case for compare mode and the baseline file was to be able to run local comparisons between different builds. Having the file outside git inside is allowing bundle-stats to use it even after a branch change.

Can you please tell me more about your use case? Personally, I don't see too many benefits in committing the file, but I don't think the change will impact the current behaviour. Feel free to create a pull request & let me know if you have any questions ;)

**Comment by B3zo0** [comment]
I'm going to close this issue because I went with https://relative-ci.com/documentation/setup/webpack-plugin
It is easier and cleaner approach.

**Comment by romariolopezc** [comment]
Is there a way to specify a different baseline? Even outside the directory, like the `~/.cache`.

Sometimes my build fails and I do `rm -rf node_modules` and the baseline file is gone :cry:

**Comment by vio** [comment]
@romariolopezc there are couple ways to achieve this now:

1. If you use the CLI, you can pass the baseline path as the last argument

```shell
bundle-stats CURRENT_WEBPACK_STATS_PATH BASELINE_WEBPACK_STATS_PATH
```

2. bundle-stats is using [find-cache-dir](https://www.npmjs.com/package/find-cache-dir) to resolve the cache directory, you can override that at run time with [`CACHE_DIR` env variable](https://github.com/avajs/find-cache-dir#findcachediroptions)
