### ISSUE TITLE
[gatsby-plugin] Nothing in outDir

### ISSUE THREAD

**Issue by muuvmuuv** [relative-ci/bundle-stats#648]
So I followed the instructions but couldn't see any files generated in the specified `outDir` and neither some UI server that open in the browser.

Here's my project: https://github.com/muuvmuuv/portfolio/tree/development

Just add your plugin.

```
    {
      resolve: 'gatsby-plugin-bundle-stats',
      options: {
        // https://github.com/relative-ci/bundle-stats/tree/master/packages/webpack-plugin
        outDir: `${__dirname}/reports`,
      },
    },
```

**Comment by vio** [comment]
Hi @muuvmuuv,  `outDir` needs to be relative to your build folder

https://github.com/relative-ci/bundle-stats/tree/master/packages/webpack-plugin#bundlestatswebpackpluginoptions

For your case, the config should be:
```
    {
      resolve: 'gatsby-plugin-bundle-stats',
      options: {
        // https://github.com/relative-ci/bundle-stats/tree/master/packages/webpack-plugin
        outDir: `reports`,
      },
    },
```

i just noticed that gatsby plugin doc is pointing to the v1 package, will fix that ;)

**Comment by muuvmuuv** [comment]
Oh yes, sorry, but there is still no file generated.

**Comment by vio** [comment]
@muuvmuuv I cloned https://github.com/muuvmuuv/portfolio/tree/development and ran `npm run build`. If the build is finishing successfully, the report is correctly generated:

![](https://www.dropbox.com/s/l5cb0f3xfjfzh6a/Screenshot%202020-03-05%2000.23.45.png?raw=1)

**Comment by muuvmuuv** [comment]
Uff... I have looked into the wrong directory ^^ thank you!
