### ISSUE TITLE
baseline-Feature doesn't work with Webpack output-Path

### ISSUE THREAD

**Issue by HopFlash** [relative-ci/bundle-stats#688]
If I use something like this in my Webpack config:
`output: {
        path: 'P:\\Development\\Client\\static',
        filename: '[name].bundle.js',
        chunkFilename: '[name].bundle.js',
},`
and the bundle-stats "baseline" feature then I get an error message because of two absolute paths mangled:
`Error: EINVAL: invalid argument, mkdir 'P:\Development\Client\static\C:\MainClient\client\node_modules\.cache\bundle-stats'`

bundle-stats version: 1.15.6

**Comment by vio** [comment]
Hi @HopFlash! We rely on [`find-cache-dir`](https://www.npmjs.com/package/find-cache-dir) to get the absolute path to the caching folder, probably something is failing for your setup.

Can you try to install the latest `bundle-stats` ([cli](https://www.npmjs.com/package/bundle-stats) or [webpack-plugin](https://www.npmjs.com/package/bundle-stats-webpack-plugin)) and see if you are still getting the error? There were couple `find-cache-dir` updates since `bundle-stats@1.15.6`.

**Comment by HopFlash** [comment]
Hi @vio! Thx for the fast reply.
I updated now to version 2.1.1 and there is the same error.
I have a relative small webpack config and the only path I set is the output path.
Should I report a bug at find-cache-dir ? I don't think so, because if you get the absolute path to the caching folder (whats seems to work fine) then the bug is that you concat this absolute path with the absolute output path.
Or is this concatenation done by find-cache-dir?

**Comment by vio** [comment]
Thanks for checking! I will need to investigate a bit deeper, the behaviour is slightly different for cli / webpack-plugin. Can you please tell me if you use the cli or the webpack plugin?

**Comment by HopFlash** [comment]
its the "bundle-stats-webpack-plugin".

I uploaded my webpackconfig(s) for you. Perhaps there are other interactions from other parts:

[webpack.common.config.js.txt](https://github.com/relative-ci/bundle-stats/files/4415715/webpack.common.config.js.txt)
[webpack.dev.config.js.txt](https://github.com/relative-ci/bundle-stats/files/4415716/webpack.dev.config.js.txt)

if you need anything more please tell me.

My "workaround" is an empty output path (then all works fine).

**Comment by HopFlash** [comment]
@vio it looks like that the path function under windows with different drive letters has problems to find path.relative (and I don't see how that can be made correctly if not giving back the absolute path).
there is a path.win32 but that wouldn't help I think.
but is there any need to use path.relative here when getting an absolute path in "from"?
https://github.com/relative-ci/bundle-stats/blob/a053dd2317a29778ccfb90959cf1081fdd47c2e4/packages/cli-utils/src/baseline.js#L14

**Comment by vio** [comment]
@HopFlash thanks for looking into it, I think you are right about the culprit. We need to extract the relative path in order to pass it to the compilation assets - https://github.com/relative-ci/bundle-stats/blob/a053dd2317a29778ccfb90959cf1081fdd47c2e4/packages/webpack-plugin/src/webpack-plugin.js#L85

**Comment by vio** [comment]
@HopFlash I managed to build an example project (`output.path` set and baseline enabled) on windows:

https://github.com/relative-ci/example-bundle-stats-webpack-config/blob/master/webpack.config.js#L9-L17

https://travis-ci.org/github/relative-ci/example-bundle-stats-webpack-config/jobs/669909279#L90

Also, I manually set the output path and it worked ok:
![](https://www.dropbox.com/s/kn1y78av70ssg8e/Screenshot%202020-04-02%2000.47.30.png?raw=1)

I would recommend you to try couple other things:
1. use a different directory, maybe on a different disk
2. use `path.join` or `path.resolve` with `__dirname` if possible

Let me know how it goes if you get the chance to do it ;)

**Comment by HopFlash** [comment]
@vio if my cache path is on my drive C and my webpack output path too then all works fine...but the crux is the situation where my cache path is still on drive C but my output path is on drive P or something else...then there is no relative path in an windows enviroment possible and the concatenation produce two mangled absolute paths.

My scenario is an dev enviroment where my Delphi application works among other things as the webserver to show embedded webpages. When I'm developing and debugging I need to work with the (delphi) server side and the react client side and webpack watch server regenerates the files to serve. Drive P is the dedicated Delphi Application workspace (created with "subst" because I can change it for dev, rc or prod enviroment) and so I set my output path to the path on drive P but on P is no cache path.

**Comment by vio** [comment]
@HopFlash I think you should be able to workaround this issue by having the baseline and the webpack output on the same disk. You can override `find-cache-dir` path with [`CACHE_DIR` env variable](https://github.com/avajs/find-cache-dir#findcachediroptions).
