### ISSUE TITLE
Question - Can I run this on existing stats.json file.

### ISSUE THREAD

**Issue by gs-akhan** [relative-ci/bundle-stats#722]
Hi,
I have an angular project which generates stats.json file, How can I invoke bundle-stats on that file. 

Thanks

**Comment by vio** [comment]
@gs-akhan you can use the [CLI](https://github.com/relative-ci/bundle-stats/tree/master/packages/cli#usage) to generate the report ;)

**Comment by gs-akhan** [comment]
Cool.
So basically I had to run `bundle-stats` inside the dist folder and it did the trick, it picked up that stat-json file automatically. thats pretty rad. !!
Thanks
