### ISSUE TITLE
Typescript type definitions improvements

### ISSUE THREAD

**Issue by mwgamble** [relative-ci/bundle-stats#984]
Unfortunately it appears the current set of typescript definitions for the webpack plugin aren't compatible with webpack 5. I have tested a bunch of updates to the type definitions, but I don't think they're compatible with webpack 4.

With version 5, webpack have moved to bundling their own type definitions with the webpack package. From what I can tell, this means that trying to provide type definitions that support both versions at the same time is an intractable problem.

My personal inclination is that the way to go is to support only the new version, as everyone will need to upgrade eventually. I'm relatively new to this ecosystem however, so I don't know what the expected support timeline is for something like webpack. I'd appreciate the thoughts of the maintainers before I submit a pull request.

**Comment by vio** [comment]
@mwgamble can you please share what package / version are you using and what error are you getting? Also, are you using a javascript or a typescript config file?

The webpack plugin typings are nor relying directly on webpack types, but is using a custom one as a `Partial` - https://github.com/relative-ci/bundle-stats/blob/e0141c411e1af42b2f456ec9a51809bd5fec8b6d/packages/webpack-plugin/typings.d.ts#L2.

**Comment by mwgamble** [comment]
I'm talking about my proposed updates to the typescript type definitions, not what is currently there. Sorry if I didn't make that clear in my original message.

I'm using the very latest version of the package (v2.3.0), and configuring webpack using a typescript file. The type definitions provided with this package did not work out of the box for me. The primary issue is the lack of an `apply` method in the type definition for the plugin class. There are a few secondary issues that I would like to improve upon as well.

I have already updated the relevant type definitions and am using them locally. I would like to share them with the world in the form of a PR to this repository, but they rely on webpack 5 and it isn't particularly feasible to include support for webpack 4. My question to the maintainers is: is support for webpack 4 important moving forward?

**Comment by vio** [comment]
>  The type definitions provided with this package did not work out of the box for me. The primary issue is the lack of an apply method in the type definition for the plugin class. There are a few secondary issues that I would like to improve upon as well.
Yes, we are currently providing type definitions only for the plugin options...

>  I would like to share them with the world in the form of a PR to this repository, but they rely on webpack 5 and it isn't particularly feasible to include support for webpack 4. 
A PR with support for webpack 5 typings will be really appreciated ;)

> My question to the maintainers is: is support for webpack 4 important moving forward?
We are going to support both versions for a while, but it makes a lot of sense for the plugin to depend on [webpack 5](https://github.com/relative-ci/bundle-stats/blob/master/packages/webpack-plugin/package.json#L60). For the users with webpack 4, we can provide instructions how to ignore the type check and / or release a major version.

**Comment by zelenkoff** [comment]
Is there some updates? I mean, I have some errors inside typings.d.ts and that would be nice if you can help me to solve them :)
![Screenshot 2020-11-13 at 20 09 49](https://user-images.githubusercontent.com/11873118/99100007-4b411c80-25ec-11eb-90e7-90762b5dc120.png)

And yes, plugin typings are nor relying directly on webpack types what a little bit confusing.

**Comment by vio** [comment]
@zelenkoff didn't manage to look into it yet, my plan is to handle it along with https://github.com/relative-ci/bundle-stats/issues/1029 soon. 

Will help a lot if you can provide an example of your webpack.config.ts/tsconfig.json.

**Comment by vio** [comment]
already fixed by https://github.com/relative-ci/bundle-stats/pull/1958
